language: python
#dist: xenial
#language: python
#cache: pip
#env:
#- TEST_CMD="coverage run tests/test_black.py"
#install:
#- pip install coverage coveralls flake8 flake8-bugbear mypy black
##- pip install -e '.[d]'
#script:
#- $TEST_CMD
#after_success:
#- coveralls
#notifications:
#  on_success: change
#  on_failure: always
#matrix:
#  include:
#    - name: "mypy"
#      python: 3.6
#      env:
#        - TEST_CMD="mypy black.py blackd.py tests/test_black.py"
##    - name: "black"
##      python: 3.7
##      env:
##        - TEST_CMD="black --check --verbose ."
#    - name: "flake8"
#      python: 3.7
#      env:
#        - TEST_CMD="flake8 black.py blackd.py tests/test_black.py"
#    - name: "3.6"
#      python: 3.6
#    - name: "3.7"
#      python: 3.7
#    - name: "3.8-dev"
#      python: 3.8-dev
#  # aiohttp currently has a bug affecting 3.8
#  allow_failures:
#    - name: "3.8-dev"
#      python: 3.8-dev
